- src/main/scala/io/qbeast/spark/sql/qbeast/BlockWriter.scala
- src/main/scala/io/qbeast/spark/sql/qbeast/QbeastOptimizer.scala
- src/main/scala/io/qbeast/spark/sql/qbeast/QbeastWriter.scala
- src/test/scala/io/qbeast/spark/utils/BlockWriterTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSnapshotTest.scala
This PR makes the BlockWriter to use relative names for the data files.
In addition it also changes QbeastSnapshotTest, because it was failing on my machine due to rounding errors while merging the weight estimations of the partitions.
> 19 delta log should use relative paths instead of absolute

- src/main/scala/io/qbeast/spark/index/query/QuerySpecBuilder.scala
- src/test/scala/io/qbeast/spark/QbeastIntegrationTestSpec.scala
- src/test/scala/io/qbeast/spark/index/query/QuerySpecBuilderTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastFilterPushdownTest.scala
In #58 we found a match error between spark `UTF8String` type and **core** types for transforming the column values. This affects only the query part, because is the only one that uses the spark unsafe types for parsing information. 
This PR solves the issue and adds tests that should fail on the `main` branch.
> Match error on filtering string indexed columns

- .github/workflows/test-and-publish-artifact.yml
Adding a simple check for the repository name to avoid running the `sbt publish` on the repository forks' CI. The syntax used is the one from [GitHub Actions Quickstart](https://docs.github.com/en/actions/quickstart).
Fixes #52
> Add check to publish only when repository is "Qbeast-io/qbeast-spark"

- core/src/main/scala/io/qbeast/core/model/QbeastBlock.scala
- core/src/main/scala/io/qbeast/core/model/QbeastFile.scala
- core/src/main/scala/io/qbeast/core/model/RevisionClasses.scala
- core/src/main/scala/io/qbeast/core/model/Weight.scala
- core/src/test/scala/io/qbeast/core/model/QbeastBlockTest.scala
- core/src/test/scala/io/qbeast/core/model/QbeastFileTest.scala
- src/main/scala/io/qbeast/spark/delta/CubeDataLoader.scala
- src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala
- src/main/scala/io/qbeast/spark/delta/IndexStatusBuilder.scala
- src/main/scala/io/qbeast/spark/delta/OTreeIndex.scala
- src/main/scala/io/qbeast/spark/index/query/QueryExecutor.scala
- src/main/scala/io/qbeast/spark/index/writer/BlockWriter.scala
- src/main/scala/io/qbeast/spark/utils/Params.scala
- src/test/scala/io/qbeast/spark/QbeastIntegrationTestSpec.scala
- src/test/scala/io/qbeast/spark/delta/OTreeIndexTest.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSnapshotTest.scala
- src/test/scala/io/qbeast/spark/index/CubeWeightsIntegrationTest.scala
- src/test/scala/io/qbeast/spark/index/OTreeAlgorithmTest.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
This PR fixes #61 
The changes made are:
- `OTreeIndex` now extends `FileIndex` instead of `TahoeLogFileIndex`
- QueryExecutor doesn't need `previouslyMatchedFiles` anymore
- `QbeastFile` now it's named `QbeastBlock`
- Add more metadata to the `QbeastBlock`: **size** and **modificationTime**
- `CubeStatus` now contains `QbeastBlock` objects instead of the path
> Avoid repeated reading of the DeltaLog

- src/main/scala/io/qbeast/spark/QbeastTable.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Related to #43, this PR adds new methods to `QbeastTable` that allows both developers and users to understand the metadata of qbeast, such as:
```scala
val qbeastTable = QbeastTable.forPath(spark, path)
qbeastTable.indexedColumns() // Outputs the actual indexed columns
qbeastTable.cubeSize() // Outputs the actual cube size
qbeastTable.revisionsID() // Outputs the list of revision identifiers available for a table
qbeastTable.latestRevisionID() // Outputs the latest revision identifier available for a table
```
Any suggestion is welcome! Feel free to ask for metadata information that would be relevant to you :smile:
> Easier information API

- core/src/main/scala/io/qbeast/core/model/CubeWeights.scala
- core/src/test/scala/io/qbeast/core/model/CubeWeightsBuilderTest.scala
The `CubeWeights.update` method flushes the `queue` into the `resultBuffer` when its size exceeds a predetermined `bufferSize`.
However, aside from adding the current elements to the `resultBuffer`, it also duplicates the current elements of the `buffer`. Which greatly increases the amount of memory required to do the operations.
```scala
resultBuffer ++= results()
// results() = resultInternal ++ resultBuffer
```
Instead of `resultBuffer ++= results()`, it should be `resultBuffer ++= resultInternal()`.
Solve Issue #84
> Replace `result` with `resultInternal` for `CubeWeights`

- core/src/main/scala/io/qbeast/core/keeper/Keeper.scala
- core/src/main/scala/io/qbeast/core/keeper/LocalKeeper.scala
- core/src/main/scala/io/qbeast/package.scala
- src/main/scala/io/qbeast/context/QbeastContext.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
This PR is changing **ONLY the API** to connect to the Keeper. It does not introduce any logic. 
PR #77 is the one solving #41. Here I only take care of **matching calls between the different libraries** we want to implement. 
In order to delegate the maintenance of the index to a **Keeper instance**, this is the **configuration** you need to use:
```bash
$SPARK_HOME/bin/spark-shell --master local[*]\
--packages io.delta:delta-core_2.12:1.0.0,io.qbeast:qbeast-spark-keeper_2.12:0.1.0-a2\
--jars ./target/scala-2.12/qbeast-spark-assembly-0.2.0.jar\
--conf spark.sql.extensions=io.qbeast.spark.internal.QbeastSparkSessionExtension\
--conf spark.qbeast.keeper.host=localhost\
--conf spark.qbeast.keeper.port=50051
```
As you can see, there's **three new parameters:**
1.` --packages …
> Keeper Integration API

- build.sbt
The current version of scaladoc (`sbt unidoc`) generates HTML documents like the one in the screenshot below. My idea is to include in these some information about the **qbeast-spark version**, both in the **header** and the **footer** of the files:
Any suggestions or modifications are more than welcome!☺️
> Headers and footers for scaladoc generation, including version in HTML

- CONTRIBUTING.md
- README.md
After merging #96 I realized that there was still a reference to packaging in the README.md. Sorry about that!🙏🏼
I removed this reference, along with a redundant step in CONTRIBUTING.md, which was mentioning "git clone" when it was not required.
Any suggestions or proposed changes are more than welcome!
> Remove "project packaging" from README, as it is now available in Maven

- core/src/main/scala/io/qbeast/core/model/CubeWeights.scala
- src/test/scala/io/qbeast/spark/index/CubeWeightsIntegrationTest.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSamplingTest.scala
When the number of elements in a table is large, the `groupCubeSize` used by `CubeWeightsBuilder` tends to 1. This can leads to a large number of estimated Cube Weight pairs that can cause OOM errors.
For instance, using default values for `bufferCapacity` and `desiredCubeSize`, a table with 2600M records split between 1200 partitions, the `groupCubeSize` is 190. The algorithm estimates 37K cubes, among which only around 1K are used. The workaround is to set a minimum value for `groupCubeSize`, for instance 1000, so the number of estimated cubes won't be as large. Using this setting, the number of estimated cubes is reduced to about 5K.
Test added:
Using default `bufferCapacity` and `DesiredCubeSize`, make sure that the minimum value for `groupCubeSize` is respected for different …
> Add lower bound for groupCubeSize

- core/src/main/scala/io/qbeast/core/model/QuerySpace.scala
- core/src/test/scala/io/qbeast/core/model/QuerySpaceFromToTest.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
When filtering with the max value from an indexed column, the QuerySpace filtering doesn't address the case because the right limit of a cube is always excluded.
The issue is addressed now by adding an additional condition where if the range left limit and the cube right limit are both 1.0, then we take the cube.
Fixes #111 
Test added to `QueryExecutorTest.scala`
* Spark Version: 3.1.1.
* Hadoop Version: 3.2.0
* Local test
> Space limit

- core/src/main/scala/io/qbeast/core/transform/HashTransformation.scala
- core/src/test/scala/io/qbeast/core/transform/HashTransformationTest.scala
- src/test/scala/io/qbeast/spark/index/TransformerIndexingTest.scala
Fixed issue #112 
Describe the change you're making: how it affects the API, user experience...
It is a bug fix. We were using the method Random.nextString(10) to generate a random string for null values in hashed columns (such as `string` or specific `hash(x)`). Aside from the problems described in #112, according to the documentation this method is not recommended to be used in anything important.
Better to use the Random Int approach. 
- [ x ] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [ x ] Add tests.
- [ x ] Your branch is updated to the main branch (dependent changes have been merged).
Please describe …
> Change random generation in Hash null values

- core/src/main/scala/io/qbeast/core/model/CubeWeights.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSamplingTest.scala
Using 1000 as the lower-bound value for `groupCubeSize` is performing poorly for the `DoublePass` analyzer when it comes to respecting the `desiredCubeSize` of the index.
We propose to use a smaller value, 30, for the lower-bound. The change is tested against the TPC-DS 1tb store_sales dataset. The average cube size per level is improved in comparison to using gcs=1000.
* Spark Version: 3.1.3
* Hadoop Version: 3.2
* Cluster or local: Tested in both scenarios
> User a smaller lower-bound for groupCubeSize

- docs/QbeastTable.md
- src/main/scala/io/qbeast/spark/QbeastTable.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Modify index metrics computation. Some others statistics are added since during many experiments they are found useful.
Changes made:
- Add `L1`, `L2` errors to measure how inner cube sizes deviate from the `desiredCubeSize`, values are between 0 and 1.
- For inner cubes, add a method to display average normalizedWeight and cube size per level
- Compute `depthOnBalance` using geometrics sum since many indexes don't have a high number of levels
- Add test for single cube tree
How to use:
```scala
import io.qbeast.spark.QbeastTable
val path = "yourTablePath"
val metrics = QbeastTable.forPath(spark, path).getIndexMetrics()
println(metrics)
```
* Spark Version: 3.1.3
* Hadoop Version: 3.2
> Modify index metrics

- src/main/scala/io/qbeast/spark/delta/IndexStatusBuilder.scala
- src/test/scala/io/qbeast/spark/delta/IndexStatusBuilderTest.scala
Fixes issue #119 
It is a **bug fix** for the construction of the `IndexStatus` when the appended data falls into the same revision (or when one cube has multiple blocks and has to compute the `maxWeight` of the whole). 
I write a test reproducing the bug in #119. It's under `delta` test package and has the name `IndexStatusBuilderTest`. I also checked the test for any other anomalies that may happen (such as cubes disappearance and inconsistency on the index).
* Spark Version: 3.1.2
* Hadoop Version: 3.2.0
> Fixing bug with IndexStatusBuilder

- src/main/scala/io/qbeast/spark/QbeastTable.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Fix #122, convert map.key from set to seq before mapping.
Bug Fix
Please describe the tests that you ran to verify your changes.
Test added to QbeastTableTest to account for scenarios where we have inner nodes but avgFanout is smaller than 1.0.
* Spark Version: 3.1.3
* Hadoop Version: 3.2
> Fix fanout

- core/src/main/scala/io/qbeast/core/transform/LinearTransformation.scala
- core/src/main/scala/io/qbeast/core/transform/LinearTransformer.scala
- core/src/main/scala/io/qbeast/core/transform/Transformation.scala
- core/src/test/scala/io/qbeast/core/transform/LinearTransformationTest.scala
- src/test/scala/io/qbeast/spark/index/TransformerIndexingTest.scala
Fixes #128. 
When indexing a column with the same value, an IdentityTransformation is instantiated. A Transformation is in charge of mapping the original values of the column to a [0.0, 1.0] space. In the case of IdentityTransformation, the method was returning the `value.byteValue()`, which can give you a `Double` up to 2^8. 
We solved this by changing `IdentityTransformation` to `IdentityToZeroTransformation` and returning 0.0 if the number corresponds to the transformation value.
- I changed one line of an existing test because this was badly designed. It checked if qbeast could index a column with the same value, but that value was 1. So, when transforming the value, it was in the [0.0, 1.0] range and no …
> Fixed indexing columns with unique values

- src/main/scala/io/qbeast/spark/internal/sources/QbeastDataSource.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
- src/test/scala/io/qbeast/spark/internal/sources/QbeastDataSourceTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastDataSourceIntegrationTest.scala
Fixes #81.
As described in #81, we want the `Append` operations to existing qbeast tables to be able to omit providing values for `desiredCubeSize` and `columnsToIndex`, if there's no desire to create a new revision.
Instead of
```
df.write
.mode("append")
.format("qbeast")
.option("cubeSize", cs)
.option("columnsToIndex", cti)
.save("path-to-existing-qtable")
```
we want to be able to just do the following instead:
```
df.write
.mode("append")
.format("qbeast")
.save("path-to-existing-qtable")
```
If the user was to provide any value for `cubeSize` and/or `columnsToIndex` when appending, then they will be respected. If the values provided are different than that from the last revision, a new revision should be created for the Append operation.
My assumption for this PR is that , at the …
> Infer parameters when appending

- core/src/main/scala/io/qbeast/core/model/QuerySpace.scala
- core/src/test/scala/io/qbeast/core/model/QuerySpaceFromToTest.scala
- src/main/scala/io/qbeast/spark/index/query/QuerySpecBuilder.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
- src/test/scala/io/qbeast/spark/index/query/QuerySpecBuilderTest.scala
Close #126
New feature - adding filtering support for `GreaterThan` and `LessThanOrEqual`.
`GreaterThan` is achieved by its simple addition to `from` filter selection, while the addition of `LessThanOrEqual` requires extending `to` by `epsilon`.
The value of `epsilon` is set to `1.1103e-16` for it's about to be the smallest number that satisfies `t < t + epsilon`(with `t = 1.0` or any one decimal point).
The drawback of this approach is that we might occasionally read more cubes than we should, though the probability is low: when using `LessThanOrEqual` and `t <= ct < t + epsilon`, we include the sibling cube (one that has `cf <= t + epsilon`) when we shouldn't. It takes about `log2(1 / epsilon) ~= 53` levels for the cubes to start having dimensions smaller than epsilon; in that case, …
> 126 enrich filtering support

- CONTRIBUTING.md
- README.md
- build.sbt
- docs/AdvancedConfiguration.md
- docs/Quickstart.md
- src/main/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalog.scala
- src/test/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogIntegrationTest.scala
In this PR, we are modifying the `QbeastCatalog` to process also writes in Delta (or other formats such Iceberg or Hudi once they're integrated). 
It is an improvement of an existing Catalog feature. Instead of managing two catalogs at the same time, the user would only need to set up one by adding the following configuration to any Spark Application:
`--conf spark.sql.catalog.spark_catalog=io.qbeast.spark.internal.sources.catalog.QbeastCatalog`
Then, the user can create `qbeast` tables and `delta` tables with either DataFrame API or SQL:
```scala
data.write.format("delta").saveAsTable("delta_table")
data.write
.format("qbeast")
.option("columnsToIndex", "id")
.saveAsTable("qbeast_table")
```
```scala
spark.sql(
s"CREATE TABLE student (id INT, name STRING, age INT) USING qbeast " + …
```
> Unified Catalog

- core/src/main/scala/io/qbeast/core/model/QuerySpace.scala
- core/src/test/scala/io/qbeast/core/model/QuerySpaceFromToTest.scala
- src/main/scala/io/qbeast/spark/index/query/QueryExecutor.scala
- src/main/scala/io/qbeast/spark/index/query/QuerySpec.scala
- src/main/scala/io/qbeast/spark/index/query/QuerySpecBuilder.scala
- src/test/scala/io/qbeast/spark/index/query/QuerySpecBuilderTest.scala
The construction of IndexStatus when the entire Revision is out of query space is a waste.
The changes from this PR filter the Revisions out of the query space before their corresponding index construction from the log and cube filtering.
**Improvement for filtering**
- Test 1: Modify QuerySpaceFromToTest to skip Revisions that create EmptySpace instances for a given query. Revisions that create AllSpace instances don't need to traverse the index; they can return all FLOODED blocks directly.
- Test 2: QuerySpecBuilderTest: Filter QuerySpaces that are not QuerySpaceFromTo
* Spark Version: 3.1.2
* Hadoop Version: 3.2
* Cluster or local: Local
> Filter revisions through the creation of empty query spaces

- README.md
- build.sbt
- docs/Quickstart.md
This PR is to fix the documentation with the new release version `0.3.1`. 
I've missed the new merge commit 0bdee8eafb31836e1fab10badf1b3b870bb5caee in the `0.3.0 `released package. That's why the final version for the **latest release is 0.3.1** (as it does not break any API, it only adds a new feature to the Catalog). Sorry for the inconvenience.  
Thanks to all the collaborators for making this possible, and Merry Christmas!
> Change version and documentation

- docs/QbeastTable.md
- src/main/scala/io/qbeast/spark/QbeastTable.scala
- src/main/scala/io/qbeast/spark/utils/IndexMetrics.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Fixes #142 
Add more index metrics such as indexingColumns, level cube count, level cube size deviation, and cube size metrics for the leaf cubes.
Example index metrics output:
```
OTree Index Metrics:
dimensionCount: 2
elementCount: 2879966589
depth: 8
cubeCount: 13141
desiredCubeSize: 500000
indexingColumns: ss_sold_date_sk,ss_item_sk
avgFanout: 4.0
depthOnBalance: 1.206019253488489
Cubes size stats:
Quartiles:
- min: 456367
- 1stQ: 498510
- 2ndQ: 499954
- 3rdQ: 501410
- max: 536430
Stats:
- count: 3285
- l1_dev: 0.00449603896499239
- l2_dev: 1.3487574366807247E-4
Level-wise stats:
level, avgCubeSize, stdCubeSize, cubeCount, avgWeight:
- 0:	497810,		4442,		1,	1.7361319627929786E-4
- 1:	494798,		6480,		4,	8.689350799817908E-4
- 2:	499781,		3871,		16,	0.003668841950401859
- 3:	500516, …
```
> Enrich index metrics

- src/main/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogUtils.scala
- src/test/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogIntegrationTest.scala
This PR fixes #165 
When creating an external table with an already populated directory, Qbeast was missing the schema in the final Catalog entry.
We add a method to detect this specific situation and update the service accordingly.  
A new test is added in `QbeastCatalogIntegrationTest` in which we try to create an external table without schema.
> Create External Table without schema [Spark]

- src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala
- src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala
- src/main/scala/io/qbeast/spark/internal/QbeastOptions.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
- src/test/scala/io/qbeast/spark/index/NewRevisionTest.scala
- src/test/scala/io/qbeast/spark/index/SparkRevisionFactoryTest.scala
Fixes #176
#176 is caused by `calculateRevisionChanges` not being able to detect a change of revision because the revision used is already updated with valid columnStats.
The solution provided here is to directly update the `RevisonID` when dimension boundaries are provided for all indexing columns before any further processing. So, if there's no `SpaceChanges` detected, the revision we use would still have the proper value: `latestRevision.revisionID + 1`.
An unintended consequence of this approach would be incrementing the `RevisionID` twice if column boundaries are provided for all indexing columns but some or all are smaller than that from the actual data - once during revision creation, and again during `spaceChanges.createNewRevision`. This 'issue' has no affect on the data or the …
> Fix column stats

- src/main/scala/io/qbeast/spark/utils/IndexMetrics.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Pretty print for level-wise cube stats when computing index metrics:
From this:
```
Level-wise stats:
level, avgCubeSize, stdCubeSize, cubeCount, avgWeight:
- 0:	980206,		0,		1,	8.005429992453528E-4
- 1:	980363,		660,		4,	0.0041565194852083275
- 2:	981671,		1548,		16,	0.018375531352561786
- 3:	997715,		67997,		56,	0.06759438497324209
- 4:	1000715,		70513,		84,	0.13032458088667634
- 5:	1001532,		70545,		84,	0.19846727799566344
- 6:	1015797,		93392,		84,	0.26661787450512003
- 7:	1000883,		2053,		84,	0.33609457503115037
- 8:	1000840,		1790,		84,	0.4055793517315446
- 9:	1000673,		1229,		84,	0.47510466986543376
- 10:	1000951,		1101,		84,	0.544636712225923
- 11:	1001080,		1283,		84,	0.6141759610357659
- 12:	1001121,		1178,		84,	0.6837241991124626
- 13:	1001160,		1102,		99,	0.7945777163997536
- …
```
> Align cube stats columns when printing

- core/src/main/scala/io/qbeast/core/model/QbeastBlock.scala
- core/src/test/scala/io/qbeast/core/model/QbeastBlockTest.scala
- src/main/scala/io/qbeast/spark/delta/IndexStatusBuilder.scala
- src/main/scala/io/qbeast/spark/delta/QbeastMetadataSQL.scala
- src/test/scala/io/qbeast/spark/delta/IndexStatusBuilderTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/WriteTestSpec.scala
This PR adds the information of the `CubeID` to `QbeastBlock` structure to help debugging the behaviour of the code. 
It is a change on both `core` and `spark`. It is not a breaking change, because we do not change any written information. 
Add a small test on `IndexBuilderStatusTest` in which we ensure that each `QbeastBlock` contains the correct `cubeID`.
> Add cube information to QbeastBlock

- core/src/main/scala/io/qbeast/core/model/QuerySpace.scala
- src/main/scala/io/qbeast/spark/delta/OTreeIndex.scala
- src/main/scala/io/qbeast/spark/index/query/QbeastFilters.scala
- src/main/scala/io/qbeast/spark/index/query/QueryExecutor.scala
- src/main/scala/io/qbeast/spark/index/query/QueryFiltersUtils.scala
- src/main/scala/io/qbeast/spark/index/query/QuerySpecBuilder.scala
- src/test/scala/io/qbeast/spark/delta/OTreeIndexTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/BlockWriterTest.scala
- src/test/scala/io/qbeast/spark/index/query/DisjunctiveQuerySpecTest.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
- src/test/scala/io/qbeast/spark/index/query/QuerySpecBuilderTest.scala
- src/test/scala/io/qbeast/spark/index/query/QueryTestSpec.scala
- src/test/scala/io/qbeast/spark/utils/QbeastFilterPushdownTest.scala
This PR fixes #183 . 
It includes additional functionalities on the `query` package that processes the OR query operators, creating several query spaces to iterate and union. 
The pipeline is the following:
1. SparkFilters (a sequence of `Expression`) are passed to the `OTreeIndex` from Spark Query Plan. 
2. We create a `QuerySpecBuilder`.
3. To filter the files, we load all the revisions from `QbeastSnapshot` and we build a `QuerySpec` for each of them. 
4. Now, we can have **several `QuerySpecs` for a single `Revision`**. Since the predicates contain OR's, our queries are divided into smaller filters that can be run independently. To create the QuerySpecs, we do:
i. **Split Query Filters and Weight Filters**. Weight filters are those which indicates the size of the sample. Query Filters …
> Support for OR and IN operator

- src/main/scala/io/qbeast/spark/delta/writer/SparkDeltaDataWriter.scala
In Qbeast Cloud an authorization (403 Forbidden) error occurs when reading from a bucket and writing to another. The reason is that the configuration parameter
spark.hadoop.fs.s3a.aws.credentials.provider=io.qbeast.ingestion.aws.RoleCredentialsProviderWithUri
is lost when launching write jobs with the class io.qbeast.spark.delta.writer.SparkDeltaDataWriter, and consequently the default authorization classes are used instead. This is because the hadoop configuration in use with the spark session is lost due to the use of the method call Job.getInstance() of the class org.apache.hadoop.mapreduce.Job, which as explained in the documentation (https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/mapreduce/Job.html#getInstance--):
Creates a new [Job] with no particular [Cluster]. A …
> Avoid losing hadoop conf in writing jobs in v0.3.2

- core/src/main/scala/io/qbeast/core/transform/LinearTransformation.scala
- core/src/main/scala/io/qbeast/core/transform/LinearTransformer.scala
- core/src/main/scala/io/qbeast/core/transform/Transformation.scala
Fixes #140 
Big fix for processing `java.time.Instant` values in rows for Transformation. 
> Add support for java.time.Instant

- build.sbt
- core/src/main/scala/io/qbeast/core/model/MetadataManager.scala
- core/src/main/scala/io/qbeast/core/model/QbeastBlock.scala
- core/src/test/scala/io/qbeast/core/model/JSONSerializationTests.scala
- core/src/test/scala/io/qbeast/core/model/QbeastBlockTest.scala
- src/main/scala/io/qbeast/spark/delta/CubeDataLoader.scala
- src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala
- src/main/scala/io/qbeast/spark/delta/IndexStatusBuilder.scala
- src/main/scala/io/qbeast/spark/delta/QbeastMetadataOperation.scala
- src/main/scala/io/qbeast/spark/delta/QbeastMetadataSQL.scala
- src/main/scala/io/qbeast/spark/delta/ReplicatedFile.scala
- src/main/scala/io/qbeast/spark/delta/SparkDeltaMetadataManager.scala
- src/main/scala/io/qbeast/spark/delta/writer/BlockStats.scala
- src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala
- src/main/scala/io/qbeast/spark/delta/writer/Compactor.scala
- src/main/scala/io/qbeast/spark/index/query/QueryExecutor.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
- src/main/scala/io/qbeast/spark/utils/Params.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSnapshotTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/SparkDeltaDataWriterTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/WriteTestSpec.scala
- src/test/scala/io/qbeast/spark/index/NormalizedWeightIntegrationTest.scala
- src/test/scala/io/qbeast/spark/keeper/ProtocolMock.scala
- src/test/scala/io/qbeast/spark/keeper/ProtocolMockTest.scala
- src/test/scala/io/qbeast/spark/table/HasConflictsTest.scala
This PR reverts the changes made on #200 because we move to a different strategy on #207 
So history is clean and we upgrade to version 0.4.0 accordingly to the next available release for Apache Spark 3.3.0 and Delta Lake 2.1.0.
> Revert #200 and new version

- src/main/scala/io/qbeast/spark/index/query/QuerySpecBuilder.scala
- src/test/scala/io/qbeast/spark/utils/QbeastFilterPushdownTest.scala
In this PR, we fixed a bug in which the creation of the range filter that creates a QuerySpace wasn't taking into account the possibility of column transformations in Spark. 
For example, imagine that we index the parameter named `column1`. If we filter by:
`regex("prefix", "column1", 1) == "a"`
Instead of filtering by the regex expression, `QuerySpaceBuilder` would understand that we are trying to filter all the values that contain ` column1 == "a"`
Describe the change you're making: how it affects the API, and user experience...
Is a bug fix.
Please describe the tests that you ran to verify your changes.
Change test that (unfortunately) passed because the filter range belonged to the same file …
> QuerySpace creation fix

- src/main/scala/io/qbeast/spark/internal/rules/QbeastAnalysis.scala
- src/main/scala/io/qbeast/spark/internal/rules/QbeastAnalysisUtils.scala
- src/main/scala/io/qbeast/spark/internal/sources/v2/QbeastWriteBuilder.scala
- src/main/scala/org/apache/spark/sql/SchemaUtils.scala
- src/test/scala/io/qbeast/spark/utils/QbeastInsertToTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSchemaTest.scala
Fixes #213 
Describe the change you're making: how it affects the API, user experience...
It is a bug fix for INSERT INTO statement when no schema is provided. 
The code searches the Spark Logical Plan for an `AppendData` operation to a `QbeastTableImpl` and applies the required casts to the input query in order to match the Schema of the Table.
NOTE: This code is retrieved from DeltaAnalysis in https://github.com/delta-io/delta/blob/512562dbd43b03bd3debcebd059ed2a36577d140/spark/src/main/scala/org/apache/spark/sql/delta/DeltaAnalysis.scala#L4 
Since all the methods were private, there was not easy way of avoiding duplication. Sorry for the inconvenience. 
Please describe the tests that you ran to verify your …
> Schema cast for appends using INSERT INTO

- docs/sample_pushdown_demo.ipynb
This PR adds Google Colab support to the Qbeast notebook demo, by adding the required pip command line.
The notebook is now working on Colab.
> Add Google Colab support to the Qbeast notebook demo 

- core/src/main/scala/io/qbeast/core/model/CubeId.scala
- core/src/test/scala/io/qbeast/core/model/CubeIdTest.scala
- core/src/test/scala/io/qbeast/core/model/JSONSerializationTests.scala
This PR fixes the implementation of `equals/hashCode` of the class `CubeId` and closes #228.
This is a fix of internal implementation, so neither public API, nor serialization format are affected.
The corner cases mentioned in the bug #228 are added to the `CubeIdTest` class.
> #228 Implementation of equals/hashCode of CubeId is fixed

- core/src/main/scala/io/qbeast/core/model/CubeId.scala
- core/src/main/scala/io/qbeast/core/transform/HashTransformation.scala
- core/src/main/scala/io/qbeast/core/transform/HistogramTransformation.scala
- core/src/main/scala/io/qbeast/core/transform/HistogramTransformer.scala
- core/src/main/scala/io/qbeast/core/transform/LinearTransformer.scala
- core/src/main/scala/io/qbeast/core/transform/StringHistogramTransformation.scala
- core/src/main/scala/io/qbeast/core/transform/StringHistogramTransformer.scala
- core/src/main/scala/io/qbeast/core/transform/Transformer.scala
- core/src/test/scala/io/qbeast/core/model/CubeIdTest.scala
- core/src/test/scala/io/qbeast/core/model/JSONSerializationTests.scala
- core/src/test/scala/io/qbeast/core/transform/EmptyTransformationTest.scala
- core/src/test/scala/io/qbeast/core/transform/StringHistogramTransformationTest.scala
- core/src/test/scala/io/qbeast/core/transform/TransformerTest.scala
- docs/AdvancedConfiguration.md
- src/main/scala/io/qbeast/spark/delta/QbeastMetadataOperation.scala
- src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala
- src/test/scala/io/qbeast/spark/index/SparkRevisionFactoryTest.scala
- src/test/scala/io/qbeast/spark/index/TransformerIndexingTest.scala
This PR introduces a new **String** `Transformation` that uses String histograms for value mapping.
(Backport the feature from `main-1.0.0`)
A sorted sequence of distinct string values should be provided to map String values to the space.
The sequence is treated as an equal-width histogram for the column to index.
To transforma a given **String** value, we look for its **insertion position** within the sequence using binary search:
```scala
val hist = ["a", "b", "c", "d", "e"]
val coordinate = hist.search("b").insertionPoint.toDouble / (hist.length - 1) // 0.25
```
Values that are not contained within the limits of the histogram are mapped to their corresponding extremes, i.e. `0.0` or `1.0`. 
To use the feature, we build the histogram and provide it as part of `columnStats` when writing. …
> Backport string hist encoding to main

- README.md
The multi line code can't be pasted from the README in the examples.
I also fixed the qbeastTable variable name.
> Fix README for working code copy/paste in Spark shell and instructions

- src/main/scala/io/qbeast/spark/delta/DeltaStagingUtils.scala
- src/main/scala/io/qbeast/spark/delta/OTreeIndex.scala
- src/test/scala/io/qbeast/TestUtils.scala
- src/test/scala/io/qbeast/spark/delta/OTreeIndexTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastDeltaStagingTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastFilterPushdownTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSamplingTest.scala
Fixes #235
It is an enhancement, it does not affect the current writing algorithm/format.
Added test to `OTreeIndexTest` to check if staging files are filtered properly.
> Add Delta Data Skipping on Staging Area

- core/src/main/scala/io/qbeast/core/model/MetadataManager.scala
- core/src/main/scala/io/qbeast/core/model/QbeastCoreContext.scala
- docs/AdvancedConfiguration.md
- src/main/scala/io/qbeast/context/QbeastContext.scala
- src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- src/main/scala/io/qbeast/spark/delta/SparkDeltaMetadataManager.scala
- src/main/scala/io/qbeast/spark/delta/StagingDataManager.scala
- src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala
- src/main/scala/io/qbeast/spark/internal/QbeastOptions.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSnapshotTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/RollupDataWriterTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/WriteTestSpec.scala
- src/test/scala/io/qbeast/spark/index/CubeDomainsIntegrationTest.scala
- src/test/scala/io/qbeast/spark/index/IndexTest.scala
- src/test/scala/io/qbeast/spark/index/OTreeAlgorithmTest.scala
- src/test/scala/io/qbeast/spark/index/SparkPointWeightIndexerTest.scala
- src/test/scala/io/qbeast/spark/index/SparkRevisionFactoryTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSparkTxnTest.scala
The set of supported options is extended to let the user to control the transaction identity and thus to make the writes idempotent.
This is a new feature borrowed from Delta which adds two supported options `txnAppId` and `txnVersion` to be used to identify the write transaction. Once committed any other transaction with the same properties will be ignored as already committed. This feature allows to make the writes idempotent.
No breaking changes have been introduced.
A new integration test `io.qbeast.spark.utils.QbeastSparkTxnTest` is added to check the transaction handling.
> 243 investigate streaming options

- core/src/main/scala/io/qbeast/core/model/MetadataManager.scala
- core/src/main/scala/io/qbeast/core/model/QbeastCoreContext.scala
- docs/AdvancedConfiguration.md
- src/main/scala/io/qbeast/context/QbeastContext.scala
- src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- src/main/scala/io/qbeast/spark/delta/SparkDeltaMetadataManager.scala
- src/main/scala/io/qbeast/spark/delta/StagingDataManager.scala
- src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala
- src/main/scala/io/qbeast/spark/internal/QbeastOptions.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSnapshotTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/SparkDeltaDataWriterTest.scala
- src/test/scala/io/qbeast/spark/delta/writer/WriteTestSpec.scala
- src/test/scala/io/qbeast/spark/index/CubeWeightsIntegrationTest.scala
- src/test/scala/io/qbeast/spark/index/IndexTest.scala
- src/test/scala/io/qbeast/spark/index/OTreeAlgorithmTest.scala
- src/test/scala/io/qbeast/spark/index/SparkPointWeightIndexerTest.scala
- src/test/scala/io/qbeast/spark/index/SparkRevisionFactoryTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSparkTxnTest.scala
This is a backport of txnAppId and txnVersion support from the main-1.0.0 branch. 
This is a new feature for implementing idempotent writes backported from main-1.0.0, so it is an extension which does not introduce any changes in the data format, and it is backward compatible. The documentation is updated to provide information about the use and semantics of the txnAppId and txnVersion options.
- [ x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [ x] Add comments to the code (make it easier for the community!).
- [ x] Change the documentation.
- [ x] Add tests.
- [ x] Your branch is updated to the main branch (dependent changes have been merged).
- Test …
> 250 backport the txn app id and txn version support

- CONTRIBUTING.md
- build.sbt
This is a change in the build script that allows to publish build snapshots in the local repos. It does not affect the client code at all.
This is an enhancement that simplifies the developing applications on the top of qbeast-spark. Neither client API nor storage format are affected.
Manual testing is the only available, because it is a change in the project infrastructure.
> #256 backport to main publishing to local Ivy and Maven turned on

- src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
Fixes #259. Adds a warning entry to the system log if the txnAppId and txnVersion of the requested write are already in the transaction log.
This is a UI enhancement, that allows the operators to discover the attempts to write data that was already written before. There are no compatibility issues here.
> 259 txnAppId and txnVersion are logged with warning

- core/src/test/scala/io/qbeast/core/model/WeightAndCountTest.scala
- src/main/scala/io/qbeast/spark/index/query/QueryExecutor.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
> 261 add block filtering when sampling

- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
Convert the Seq[String] to Set[String] to reduce time complexity when filtering.
Improvement
> Convert Seq to Set to improve time complexity

- src/main/scala/io/qbeast/spark/delta/QbeastMetadataOperation.scala
- src/test/scala/io/qbeast/spark/keeper/ProtocolMockTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSparkCorrectnessTest.scala
Fixes #267
We make no metadata updates unless a write involves revision change or replication.
An appends that's unaware of the Replication that happened after its own write started will cause inconsistencies.
- An Append that neither changes the schema nor updates the Revision should not create metadata log entry.
> 267 Remove redundant metadata creations

- src/main/scala/io/qbeast/spark/delta/SparkDeltaMetadataManager.scala
- src/main/scala/io/qbeast/spark/delta/StagingDataManager.scala
- src/main/scala/io/qbeast/spark/internal/QbeastOptions.scala
- src/test/scala/io/qbeast/spark/index/DataStagingTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastDeltaIntegrationTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSparkTxnTest.scala
Add extra write options for `userMetadata`.
```scala
(df
.write
.mode("append")
.option("userMetadata", userMetadataString)
.format("qbeast")
.save("/tmp/test/")
)
```
The list of `userMetadata` can be queried as follows:
```scala
import io.delta.tables._
val deltaTable = DeltaTable.forPath(spark, pathToTable)
val fullUserMetadata = deltaTable.history().select("userMetadata")
fullUserMetadata.show()
```
This is a new feature.
> Add user metadata option

- core/src/main/scala/io/qbeast/core/model/RevisionClasses.scala
- core/src/test/scala/io/qbeast/core/model/RevisionTest.scala
Fixes #299. It compares the `columnsToIndex` to `Transformer` `columnName` or `spec` depending on user input.
Bug Fix
Test `columnsToIndex` comparison
> Issue 299: Check columnsToIndex depending on user input

- core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala
- core/src/test/scala/io/qbeast/core/model/CubeDomainsBuilderTest.scala
- core/src/test/scala/io/qbeast/core/model/WeightAndCountTest.scala
- src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala
This PR Fixes #297 by
1. As the overhead comes from `CubeStatus`, we pass the required objects directly instead of `IndexStatus`
2. Use `Broadcast` so they persist in each worker so we don't have to pass them for each task
> Issue 297: Reduce overhead for CubeDomainsBuilder instantiation

- src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala
- src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala
- src/main/scala/io/qbeast/spark/index/SparkOTreeManager.scala
- src/main/scala/io/qbeast/spark/internal/sources/QbeastDataSource.scala
- src/main/scala/io/qbeast/spark/table/IndexedTable.scala
It adds log messages to be able to trace activity when executing such as the following:
```
spark_data.write.format("qbeast")
.mode("append")
.options(**qbeast_options)
.save(output_path)
```
The code at the moment is very scarce on log messages, in factr, I couldn't find any in the part of the code I was inspecting. It is going to take multiple PRs to populate the code base with logging messages appropriately.
Fixes #288
It is adding log messages using the spark internal logging trait. As such, we have to add a line to specific classes to have them using `org.apache.spark.internal.Logging`. 
In the log messages I added so far, I have prefixed it with `Qbeast: ` to make it easier to locate the messages among all INFO messages that Spark generated. That's not ideal, and I'd much rather …
> Issue 288: Add log messages

- src/main/scala/io/qbeast/spark/delta/IndexFiles.scala
- src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala
- src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala
- src/test/scala/io/qbeast/core/model/IndexFilesTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastCompactionIntegrationTest.scala
Fixes #312 
- This is a bug fix
1. Optimizations should use `SnapshotIsolation,` which is to be found in the `CommitInfo`.
2. AddFile and RemoveFile should have `dataChange=false.`
> Issue 312: Optimization should not introduce data changes.

- src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala
- src/test/scala/io/qbeast/spark/delta/writer/RollupDataWriterTest.scala
Fixes #315 
Instead of ignoring offsets, cube element counts are computed from the extended data.
It is a bug fix: #315
Test correct rollup result: `RollupDataWriterTest`
> Issue 315: Correct cube element counts for rollup during optimization

- src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala
Fixes #317 through broadcasting rollup map and cube max Weights.
This is a bug fix - #317 
> Issue 317: Reduce optimization overhead

- CONTRIBUTING.md
- README.md
- docs/QbeastFormat.md
- docs/QbeastTable.md
- docs/Quickstart.md
Updates the documentation for 0.6.0 release. ( Also fixes #255 )
**Documentation** update (updates regarding the [Users docs](https://github.com/Qbeast-io/qbeast-spark/tree/main/docs) or the [Developer docs](https://docs.qbeast.io/), or similar).
> Issue 309: Update documentation for 0.6.0 release

- docs/AdvancedConfiguration.md
- src/main/scala/io/qbeast/spark/utils/QbeastUtils.scala
- src/test/scala/io/qbeast/spark/utils/QbeastUtilsTest.scala
Fixes #331 
New Feature, no breaking change. 
Easy API for computing the histogram for a column. Usage:
```scala
import io.qbeast.spark.utils.QbeastUtils
val brandStats = QbeastUtils.computeHistogramForColumn(df, "brand", 50)
val statsStr = s"""{"brand_histogram":$brandStats}"""
(df
.write
.mode("overwrite")
.format("qbeast")
.option("columnsToIndex", "brand:histogram")
.option("columnStats", statsStr)
.save(targetPath))
```
Test can be found in` io.qbeast.spark.utils.QbeastUtilsTest`
* Spark Version: 3.4.1
* Hadoop Version: 3.3.x
> Issue 331: Add Compute Histogram utility method

- docs/QbeastTable.md
- src/main/scala/io/qbeast/spark/QbeastTable.scala
- src/main/scala/io/qbeast/spark/utils/IndexMetrics.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Fixes #193 
This PR introduces new `IndexMetrics` statistics to account for the **multi-block files**.
Changes:
1. Add transformer type for the indexing columns
2. Add revision Id
3. Add revision bytes
4. Add block and file counts
5. Add quartiles for several metrics: element counts per cube and block, file bytes
6. Add quartile for level wise statistics
```
OTree Index Metrics:
revisionId: 1
elementCount: 309008
dimensionCount: 2
desiredCubeSize: 3000
indexingColumns: price:linear,user_id:linear
height: 8 (4)
avgFanout: 3.94 (4.0)
cubeCount: 230
blockCount: 848
fileCount: 61
bytes: 11605372
Multi-block files stats:
cubeElementCountStats: (count: 230, avg: 1343, std: 1186, quartiles: (1,292,858,2966,3215))
blockElementCountStats: (count: 848, avg: 364, std: 829, quartiles: …
```
> Issue 193: Update Index Metrics

- src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala
> Issue 333: Broadcast cube weights during optimization file writing

- src/main/scala/io/qbeast/spark/internal/commands/alterQbeastTableCommands.scala
- src/main/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalog.scala
- src/main/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogUtils.scala
- src/main/scala/io/qbeast/spark/internal/sources/v2/QbeastTableImpl.scala
- src/test/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogIntegrationTest.scala
- src/test/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogTest.scala
Fixes #339 
The command `ALTER TABLE t SET TBLPROPERTIES('k'='v')` was changing the properties at the Catalog level but not persisting them in the commit log of the table. 
It is a bug fix and it includes two more Qbeast commands: `AlterTableSetPropertiesQbeastCommand` and `AlterTableUnsetPropertiesQbeastCommand`.
This is tested in QbeastCatalogTest and QbeastSQLIntegrationTest.
* Spark Version: 3.5.0
* Hadoop Version: 3.3.4
> Issue 339: Persist property changes from SET TBLPROPERTIES operations in the _delta_log

- src/main/scala/io/qbeast/spark/internal/commands/ConvertToQbeastCommand.scala
- src/test/scala/io/qbeast/spark/utils/ConvertToQbeastTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSQLIntegrationTest.scala
Fixes #340 
Bug fix.
Locally on QbeastSQLIntegrationTest
* Spark Version: 3.5.0
* Hadoop Version: 3.3.4
> Issue 340: ConvertToQbeast should work for table paths containing namespaces

- src/main/scala/io/qbeast/spark/QbeastTable.scala
- src/test/scala/io/qbeast/spark/utils/QbeastTableTest.scala
Adds #350 
Three new methods are added to the QbeastTable interface:
```scala
import io.qbeast.spark.QbeastTable
// Init QbeastTable
val qbeastTable = QbeastTable.forPath(spark, "/tmp/dir")
qbeastTable.allRevisions() // List of Revision
qbeastTable.revision(1) // Information of Revision with ID=1
qbeastTable.latestRevision // Information of latest available revision
```
New feature.
Test on `QbeastTableTest`.
> Issue 350: Retrieve Revision information from QbeastTable

- src/main/scala/io/qbeast/core/model/ColumnToIndex.scala
- src/main/scala/io/qbeast/core/model/ColumnToIndexUtils.scala
- src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala
- src/main/scala/io/qbeast/spark/internal/QbeastOptions.scala
- src/main/scala/io/qbeast/spark/internal/rules/SampleRule.scala
- src/test/scala/io/qbeast/core/model/ColumnToIndexTest.scala
- src/test/scala/io/qbeast/core/model/ColumnToIndexUtilsTest.scala
- src/test/scala/io/qbeast/spark/index/SparkRevisionFactoryTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSamplingTest.scala
Fixes #352 
Bug Fix. 
This PR also centralizes the parsing of `ColumnToIndex` in the `QbeastOptions` case class, including a method to convert to the transformer. This is a way of using the same mechanism for parsing the string saved in the options in different places.
Tested on `QbeastSamplingTest`. It should fail with prior versions of the code.
* Spark Version: 3.5.0
* Hadoop Version: 3.3.4
> Issue 352: Sampling Error when explicit type is set in columnsToIndex

- README.md
Fixes [issue](https://github.com/Qbeast-io/qbeast-spark/issues/363) #363: Update some markdown files of Qbeast-spark repository.
This PR corrects the path used to link CONTRIBUTING.md, LICENSE.md and CODE_OF_CONDUCT.md in the README.md file so that the MDX compiler doesn't complain about any link.
For example:
```[Contribution Guide](/CONTRIBUTING.md)``` was changed into ```[Contribution Guide](./CONTRIBUTING.md)```
Please @cdelfosse @Jiaweihu08 review the changes.
Documentation update in the README.md file.
> Issue 363: Update markdown file links

- src/main/scala/io/qbeast/core/model/QbeastSnapshot.scala
- src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala
- src/main/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalog.scala
- src/main/scala/io/qbeast/spark/internal/sources/v2/QbeastTableImpl.scala
- src/test/scala/io/qbeast/spark/internal/sources/QbeastTableImplTest.scala
- src/test/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogIntegrationTest.scala
- src/test/scala/io/qbeast/spark/internal/sources/catalog/QbeastCatalogTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSQLIntegrationTest.scala
Fixes #366 
Bug fix.
Tests on `QbeastCatalogTest` and `QbeastCatalogIntegrationTest`.
> Issue 366: TBLPROPERTIES consistency between log, catalog and Qbeast internals

- docs/Quickstart.md
Add a pyspark example in the QuickStart
Docs update
> Add a PySpark example in the quickstart

- docs/AdvancedConfiguration.md
Fixes #382 .
We were calling to some non-existing methods in the [Advanced Configurations](https://github.com/Qbeast-io/qbeast-spark/blob/629e07d6ec56583e0ba2eee0f1fe7312a637b36f/docs/AdvancedConfiguration.md) file. 
Changed `val dnb = qt.denormalizedBlocks` to `val dnb = qt.getDenormalizedBlocks()` and `val qt = QbeastTable.forTable(spark, tablePath)` to `val qt = QbeastTable.forPath(spark, tablePath)`
Please review the changes @Jiaweihu08 @cdelfosse 
Describe the change you're making: how it affects the API, user experience...
Documentation change.
> Issue 382: Fix AdvancedConfiguration.md

- CODE_OF_CONDUCT.md
Fixes #384 . If we don't define a title / header of level 1 in the markdown files, the documentation website will use the name of the file as the title of the page.
So, to fix that, I defined "CODE OF CONDUCT" as the title of the file. `# CODE OF CONDUCT`
Please, review whenever you can @cdelfosse @Jiaweihu08 
I ran locally the website in my PC and made sure the new title was correctly displayed.
> Issue 384: Update CODE_OF_CONDUCT.md header

- build.sbt
Adds #388. 
Update `build.sbt` with the next version 0.8.0.
> Issue #388: Update build version to 0.8.0

- .github/workflows/test-artifact.yml
- CODE_OF_CONDUCT.md
Fixes #389. In this PR I will try to edit the CI that is executed in github actions everytime someone pushes some changes to a Pull Request in the qbeast-spark repository. If only markdown files have been modified, we will try to skip most of the steps of the worfklow.
Please review whenever you can @cdelfosse @osopardo1 
I have created a new step on the workflow. This step will check if the modified files are markdown files, if that's not the case a variable called `run tests` will be set to true so that the remaining steps can be executed by using if statements. If only .md files are modified, the `run tests`variable will remain unchanged and the next steps will be skipped.
> Issue 389: Documentation Updates should not trigger CI tests

- docs/Quickstart.md
- src/test/scala/io/qbeast/docs/DocumentationTests.scala
Adds #394 
Documentation Change. 
- Included Java, Maven/SBT, and Spark dependencies to install.
- Separate between Developer Environment and the Interactive one.
- Cover basic examples as [other Formats Quickstarts](https://docs.delta.io/latest/quick-start.html). 
- Separate code snippets into Python, Scala, and SQL
- Add specific instruction for Google Cloud Platform (GPC) and Amazon Web Services (AWS)
- Changed the current tests for the Quickstart in the `DocumentationTests` file. 
- Tested with Local deployment for `pyspark`.
- Tested with Local deployment for `spark-shell`.
- Tested with Local deployment for `spark-sql`.
> Feature #394: Revamp Quickstart with more information

- core/src/main/scala/io/qbeast/core/model/IndexFileBuilder.scala
- core/src/main/scala/io/qbeast/core/model/QbeastFiles.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaQbeastFileUtils.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaRollupDataWriter.scala
- src/main/scala/io/qbeast/table/IndexedTable.scala
- src/test/scala/io/qbeast/core/model/DenormalizedBlockTest.scala
- src/test/scala/io/qbeast/spark/delta/QbeastFileUtilsTest.scala
- src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala
Fixes issue #441 by setting `dataChange = False` during `optimize()`
Bug Fix
> Issue #441: Fix data change on optimize

- core/src/main/scala/io/qbeast/core/model/QbeastSnapshot.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala
- docs/QbeastTable.md
- src/main/scala/io/qbeast/table/IndexedTable.scala
- src/main/scala/io/qbeast/table/QbeastTable.scala
- src/test/scala/io/qbeast/spark/utils/ConvertToQbeastTest.scala
- src/test/scala/io/qbeast/spark/utils/PreCommitHookIntegrationTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastOptimizeIntegrationTest.scala
Adds #294 
New Feature. The Unindexed Files of a Qbeast Table were only optimizable from the `StagingDataManager` component. After thinking about structure and use cases, we noticed that the Staging Area has lost its original purpose (check issue #438) and that we should treat Indexed and Unindexed File separately from the Append execution. 
For that reason, we extend the interface of optimization to enable the processing of the unindexed files too. 
```scala
import io.qbeast.spark.QbeastTable
val qbeastTable = QbeastTable.forPath(spark, "/path")
qbeastTable.optimize(revisionID = 0L, fraction = <fraction_to_optimize>)
```
- `revisionID = 0L` is the selected Revision ID for Unindexed Files.
- `fraction`: Any number from 0.0 to 1.0 that we want to optimize. By default is 1.0. If it's a …
> Issue #294: Optimization of Unindexed Files [Staging Area]

- core/src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala
- src/test/scala/io/qbeast/spark/index/DoublePassOTreeDataAnalyzerTest.scala
- src/test/scala/io/qbeast/spark/index/IndexTest.scala
Fixes #467 
The estimation of cube weights when writing with qbeast consists of the following steps:
1. Compute cube domains only for the input/append data - `inputCubeDomains.` This consists of computing the `partitionCubeDomains` for each input partition and merging them by doing a group by sum to get `inputDataCubeDomains.`
2. Compute the updated cube domains of the index.
3. Compute `updatedCubeWeight` using the `updatedCubeDomains` with the following formula: `Wc = Wpc + dcs / Dc`
When there's no space change:
1. `partitionCubeDomains` should be built using the existing cube weights as a scaffold, pushing records further down the tree to maximize the precision of cube domain estimation.
2. `inputDataCubeDomains` should be merged with `existingCubeDomains` to get the …
> Issue #467: Separate index metada when creating a new Revision

- core/src/main/scala/io/qbeast/spark/index/QbeastColumns.scala
- core/src/main/scala/io/qbeast/spark/writer/IndexFileWriterFactory.scala
- core/src/main/scala/io/qbeast/spark/writer/RollupDataWriter.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaRollupDataWriter.scala
- src/test/scala/io/qbeast/spark/index/QbeastColumnsTest.scala
Fix for #463 
This PR allows table formats to specify custom filenames through a new configuration option in DataWriter. If a custom filename pattern is not provided, the default UUID.parquet format will be used, ensuring backward compatibility.
This PR updates the getRollupCubeIdUDF function to return a UUID instead of an Array[Byte]. It was found that the column added by this UDF is used solely to determine the file writer and filename. By using a UUID directly, we simplify the logic, as each unique RollupCubeID now maps to a unique UUID for filename generation.
- refactoring
> Issue #463: Support custom filename patterns in DataWriter

- core/src/main/scala/io/qbeast/core/model/DataWriter.scala
- core/src/main/scala/io/qbeast/core/model/MetadataManager.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataManager.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaRollupDataWriter.scala
- src/main/scala/io/qbeast/table/IndexedTable.scala
- src/test/scala/io/qbeast/spark/delta/DeltaRollupDataWriterTest.scala
Allows to pass the timestamp generated in the MetadataManager to the DataWriter
Fixes #465 
feature addition
> Issue #465: Allow MetadataManager to pass the commit timestamp to DataWriter

- core/src/main/scala/io/qbeast/core/model/MetadataManager.scala
- core/src/main/scala/io/qbeast/core/model/WriteMode.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataManager.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- src/main/scala/io/qbeast/table/IndexedTable.scala
- src/test/scala/io/qbeast/spark/delta/MetadataWriterTest.scala
- src/test/scala/io/qbeast/spark/delta/keeper/ProtocolMock.scala
Introduce Qbeast WriteMode to distinguish between Append, Overwrite, and Optimize operations #475 
New feature
> Issue #475: Add Qbeast WriteMode to distinguish between write operations

- core/src/main/scala/io/qbeast/spark/metadata/MetadataOperation.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataOperation.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala
- Abstract the Logic related to the configuration management from the Delta MetadataWriter Operator for Reusability #468 
Refactoring #398 
> Issue #468: Abstract Logic from MetadataWriter Operator for Reusability

- core/src/main/scala/io/qbeast/core/model/QbeastSnapshot.scala
- core/src/main/scala/io/qbeast/spark/index/strategies/SamplingListFilesStrategy.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala
- src/test/scala/io/qbeast/spark/delta/ConvertToQbeastDeltaTest.scala
- src/test/scala/io/qbeast/spark/delta/MetadataWriterDeltaTest.scala
- src/test/scala/io/qbeast/spark/delta/PreCommitHookDeltaTest.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSchemaDeltaTest.scala
- src/test/scala/io/qbeast/spark/docs/DocumentationTests.scala
- src/test/scala/io/qbeast/spark/utils/PreCommitHookIntegrationTest.scala
Add `loadConfiguration` in the QbeastSnapshot #489 
Moved a few tests to the delta folder
New feature
> Issue #489: Extend QbeastSnapshot Interface to Expose Relevant Information

- core/src/main/scala/io/qbeast/core/model/MetadataManager.scala
- core/src/main/scala/io/qbeast/core/model/QbeastSnapshot.scala
- core/src/main/scala/io/qbeast/spark/index/strategies/SamplingListFilesStrategy.scala
- core/src/main/scala/io/qbeast/spark/utils/Params.scala
- core/src/main/scala/org/apache/spark/qbeast/config/config.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataManager.scala
- delta/src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala
- src/main/scala/io/qbeast/context/QbeastContext.scala
- src/main/scala/io/qbeast/internal/commands/AlterQbeastTableCommands.scala
- src/main/scala/io/qbeast/internal/commands/ConvertToQbeastCommand.scala
- src/main/scala/io/qbeast/table/QbeastTable.scala
- src/main/scala/io/qbeast/utils/QbeastUtils.scala
- src/test/scala/io/qbeast/QbeastIntegrationTestSpec.scala
- src/test/scala/io/qbeast/catalog/QbeastCatalogIntegrationTest.scala
- src/test/scala/io/qbeast/context/QbeastConfigTest.scala
- src/test/scala/io/qbeast/spark/delta/QbeastOptimizeDeltaTest.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSchemaDeltaTest.scala
- src/test/scala/io/qbeast/spark/delta/QbeastSnapshotDeltaTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastCreateTableSQLTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastInsertToTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSnapshotTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastSparkCorrectnessTest.scala
- src/test/scala/io/qbeast/spark/utils/QbeastStagingTest.scala
- src/test/scala/io/qbeast/table/QbeastTableTest.scala
Fixes for #501 
- Removed unnecessary methods in MetadataManager
- Renamed `listStagingAreaFiles()` to `listUnindexedFiles()` in QbeastSnapshot
- Adapted tests and abstract them from delta
Code update
> Issue #501: Update delta code and tests

- src/main/scala/io/qbeast/utils/QbeastUtils.scala
Fixes #517. Restore API and mark it as deprecated.
API change.
We should restore the same tests as the original API.
> Issue #517: Restore QbeastUtil.computeHistogramForColumn method
