README.md
I miss this commit in the **documentation improvement**, sorry :smiling_face_with_tear:
=> Add quote to line in README.md

CONTRIBUTING.md, README.md, build.sbt, docs/CloudStorages.md, docs/Quickstart.md
Updating and publishing version `0.3.2` after merging #156  🥳 🥳 🥳
=> Update version to 0.3.2

src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala
Bug fix - should use tree size to determine if a cube should be assigned directly as a leaf during cube weight estimation.
Force a cube to be leaf when it has fewer than `desiredCubeSize` records left - `treeSize <= desiredCubeSize`
Bug fix
=> Use tree size to determine leaf cubes

CONTRIBUTING.md, README.md, docs/Quickstart.md
This PR changes Documentation for the new version of Qbeast-Spark and upgraded versions of Delta Lake and Apache Spark.
=> Change documentation

README.md, docs/IndexMetadataChangesInVersion1.0.0.md, docs/QbeastFormat1.0.0.md
The project documentation is extended with a document describing the index metadata changes introduced by version 1.0.0.
This is a documentation enhancement.
=> #233 The metadata changes are described in a separate document

README.md
Update README.md to use the latest Spark, Delta, and Qbeast format versions.
Doing a draft only as Qbeast spark 0.5.0 (current main) has not been published.
=> Update README.md to use the latest Spark, Delta, and Qbeast format versions

CONTRIBUTING.md, build.sbt
The change allows to publish snapshot artifacts into local Ivy and Maven repositories.
This an enhancement for development and testing. The production capabilities are not affected.
This change does not require automated testing like CI, just manual testing on the developer's machine is enough.
=> #256 publishing turned on for the qbeastSpark project

NOTICE
Adds a NOTICE file.
Fixes #272 
It does not change code, it adds a file for licensing purposes, see #272 for more detail.
NA
The build must not fail, otherwise, no further testing is necessary.
NA
=> Issue 272: Add NOTICE file

project/Dependencies.scala
=> Upgrade delta lake version

build.sbt
Single Commit to update version in main to the next 0.6.0!
=> Update version to 0.6.0

CONTRIBUTING.md
Fixes #285 : explain how we update the project version
- **Documentation** update only
=> Versioning policy documentation

.github/pull_request_template.md, CONTRIBUTING.md
This PR adds Logging documentation into the CONTRIBUTING.md file. 
Fixes #302 
=> Issue 302: Add Logging information to the Contributing guide

build.sbt
This PR updates the build version from 0.6.0 to 0.7.0.
Fixes #325
=> Issue 325: Change build version to 0.7.0

docs/Quickstart.md
Part 1/4 from issue #327.
Change on Documentation.
No test needed.
=> Issue 327: 1/4 Document Delete limitations for Qbeast

README.md
Added links to the [Qbeast Spark documentation](https://github.com/Qbeast-io/qbeast-spark/tree/main/docs)
=> Issue 360: Update README.md

README.md
Fixes a broken link in the README #365 
=> Issue 365: Fix broken link in README

CONTRIBUTING.md
Adds #361 and #359 
Documentation update!
No tests to run.
=> Issue 361 + 359: Update Release documentation

CONTRIBUTING.md
Fixes #380 . The MDX compiler complained of a html tag on the CONTRIBUTING.md file so I had to do this change:
"3. The **title of the PR** should follow the schema: Issue `<issue-number>:<PR-title>` "
Was changed to:
"3. The **title of the PR** should follow the schema: Issue `&lt;issue-number&gt;: &lt;PR-title&gt;`"
This way the compiler won't complain about nothing and the text will look like this (the issue number and the PR title text wasn't originally showing):
=> Issue 380: Update html labels

CONTRIBUTING.md, README.md, docs/QbeastFormat.md, docs/QbeastFormatChanges.md, docs/Quickstart.md
Fixes #387 (and also renames one file)
Documentation Update.
No tests needed.
=> Issue #387: Update docs to 0.7.0

CONTRIBUTING.md
Error on Markdown for Contributing.md
=> Issue #387 fix: Contributing.md

src/main/scala/io/qbeast/spark/table/IndexedTable.scala, src/test/scala/io/qbeast/spark/utils/QbeastOptimizeIntegrationTest.scala
- Fixes the dataChange flag issue #441 during `optimize()`
- Bug fix
Included a unit test
=> Issue #441: Fix dataChange flag in optimize

src/main/scala/io/qbeast/catalog/QbeastCatalog.scala, src/main/scala/io/qbeast/catalog/QbeastCatalogUtils.scala, src/main/scala/io/qbeast/internal/rules/SaveAsTableRule.scala, src/main/scala/io/qbeast/sources/v2/QbeastStagedTableImpl.scala, src/main/scala/io/qbeast/table/IndexedTable.scala, src/test/scala/io/qbeast/catalog/QbeastCatalogIntegrationTest.scala, src/test/scala/io/qbeast/catalog/QbeastCatalogTest.scala
Abstracts catalog tests from delta #477 
Included schema in the `IndexedTable` for flexibility
Refactoring (#398)
=> Issue #477: Abstract Qbeast Catalog Tests from Delta

core/src/main/scala/io/qbeast/core/model/MetadataManager.scala, core/src/main/scala/io/qbeast/core/model/QbeastCoreContext.scala, core/src/main/scala/io/qbeast/core/model/QbeastOptions.scala, core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala, core/src/main/scala/io/qbeast/spark/metadata/MetadataOperation.scala, core/src/test/scala/io/qbeast/core/model/QbeastHookLoaderTest.scala, delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataManager.scala, delta/src/main/scala/io/qbeast/spark/delta/DeltaMetadataWriter.scala, src/main/scala/io/qbeast/internal/rules/SampleRule.scala, src/main/scala/io/qbeast/sources/QbeastDataSource.scala, src/main/scala/io/qbeast/table/IndexedTable.scala, src/test/scala/io/qbeast/sources/QbeastOptionsTest.scala, src/test/scala/io/qbeast/spark/delta/DeltaRollupDataWriterTest.scala, src/test/scala/io/qbeast/spark/delta/QbeastOptionsDeltaTest.scala, src/test/scala/io/qbeast/spark/delta/QbeastSparkTxnTest.scala, src/test/scala/io/qbeast/spark/index/CubeDomainsIntegrationTest.scala, src/test/scala/io/qbeast/spark/index/IndexTest.scala, src/test/scala/io/qbeast/spark/index/OTreeAlgorithmTest.scala, src/test/scala/io/qbeast/spark/index/SparkRevisionFactoryTest.scala, src/test/scala/io/qbeast/spark/utils/QbeastSnapshotTest.scala, src/test/scala/io/qbeast/spark/writer/WriteTestSpec.scala
Fixes #503 
`QbeastOtions.columnStats` is now an instance of `Option[String]`
=> Issue #503: Move QbeastOptions to core

.github/workflows/test-artifact.yml
Fixes #516 
Build bug fix.
No tests.
=> Issue #516: Add core and delta packages to the Test Artifact

build.sbt
Fixes #530: Updates version from 0.7.0-SNAPSHOT to 0.7.2-SNAPSHOT in the `v0.7.x` branch.
=> Issue #530: Update version to 0.7.2-SNAPSHOT
